# Generated by Django 4.1.3 on 2022-12-06 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('summary', models.TextField(verbose_name='summary')),
            ],
        ),
        migrations.CreateModel(
            name='ArmorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of armor type', max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Blacksmith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
            ],
            options={
                'verbose_name': 'blacksmith',
                'verbose_name_plural': 'blacksmiths',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ArmorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique ID')),
                ('status', models.CharField(choices=[('m', 'manufacturing'), ('r', 'repairing'), ('a', 'assembled'), ('n', 'no materials')], default='m', max_length=1, verbose_name='status')),
                ('due_back', models.DateField(verbose_name='due_back')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='price')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forge.armor', verbose_name='armor')),
                ('blacksmith', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_armors', to='forge.blacksmith', verbose_name='blacksmith')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_type',
            field=models.ManyToManyField(help_text='Choose armor type for your armor', to='forge.armortype', verbose_name='armor_type(s)'),
        ),
        migrations.AddField(
            model_name='armor',
            name='blacksmith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armors', to='forge.blacksmith'),
        ),
    ]
