# Generated by Django 4.1.3 on 2022-12-07 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forge', '0002_armor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='armororder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_armors', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
    ]
