# Generated by Django 4.1.3 on 2022-12-07 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forge', '0004_alter_armor_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('content', models.TextField(max_length=10000, verbose_name='content')),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='forge.armor', verbose_name='armor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armot_reviews', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
